services:
    mollie:
        class: Usoft\IDealBundle\Driver\MollieDriver
        arguments:
            - %mollie_key%
            - %mollie_description%

    usoft.form.type.ideal:
        class: Usoft\IDealBundle\Form\Type\IDealType
        tags:
            - { name: form.type, alias: ideal }
