services:
    mollie.client:
      class: Mollie_API_Client

    mollie:
        class: Usoft\IDealBundle\Driver\MollieDriver
        arguments:
            - "@mollie.client"
            - "@router"
            - "@event_dispatcher"
            - "%mollie_key%"
            - "%mollie_description%"

    usoft.form.type.ideal:
        class: Usoft\IDealBundle\Form\Type\IDealType
        tags:
            - { name: form.type, alias: ideal }
