language: php

php:
  - 5.6

install:
  - composer require satooshi/php-coveralls:~0.6@stable

before_script:
  - mkdir -p build/logs
  - composer install

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bin/coveralls -v --exclude-no-stmt

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
